seeder:
  file: ./seeder/seeder.rb
  disabled: false

parser:
  - file: ./parser/search.rb
    page_type: search
    disabled: true

  - file: ./parser/product.rb
    page_type: product
    disabled: true